/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonCartComponent: typeof import('./../components/buttons/ButtonCartComponent.vue')['default']
    CardCartProduct: typeof import('./../components/cards/CardCartProduct.vue')['default']
    CardProducts: typeof import('./../components/cards/CardProducts.vue')['default']
    ComponentDialogComplement: typeof import('./../components/dialogs/system/ComponentDialogComplement.vue')['default']
    DrawerCartComponent: typeof import('./../components/layout/cart/DrawerCartComponent.vue')['default']
    ErrorProductNotFound: typeof import('./../components/errors/ErrorProductNotFound.vue')['default']
    NavbarFilterProducts: typeof import('./../components/layout/sections/NavbarFilterProducts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionProductsAll: typeof import('./../components/layout/sections/SectionProductsAll.vue')['default']
    SectionProductsFiltered: typeof import('./../components/layout/sections/SectionProductsFiltered.vue')['default']
  }
}
